export const contactDetailsActionTypes = {
    SET_CONTACT_NAME:"SET_CONTACT_NAME",
    SET_CONTACT_ADDRESS:"SET_CONTACT_ADDRESS",
    SET_CONTACT_EMAIL: "SET_CONTACT_EMAIL",
    SET_CONTACT_PHONE: "SET_CONTACT_PHONE",
    CLEAR_CONTACTS: "CLEAR_CONTACTS"
};